---
title: "HW 3"
author: "Bryan Mui UID 506021334"
date: "2025-10-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(psych)
```

## Whole scale cronbach's alpha

```{r}
df <- read_csv("campus climate data generated by Chat Gpt.csv")
head(df)
```

```{r}
model_df <- df %>% 
  select(1:31)

total_alpha <- alpha(model_df)

total_alpha
```

```{r}
total_alpha$alpha.drop %>%
  arrange(desc(raw_alpha))
```


## Subscale: belonging

```{r}
model_df_belong <- df %>% 
  select(1:5)

alpha(model_df_belong)
```

## Academic self-concept

```{r}
model_df_acad <- df %>% 
  select(7:12)

alpha(model_df_acad)
```

## Perceived Stress

```{r}
model_df_stress <- df %>% 
  select(13:18)

alpha(model_df_stress)
```

## Perceived Discrimmination

```{r}
model_df_disc <- df %>% 
  select(19:24)

alpha(model_df_disc)
```

## Respect for Diversity and Campus Climate

```{r}
model_df_div <- df %>% 
  select(25:31)

alpha(model_df_div)
```

```{r}
subscale_scores <- df %>%
mutate(
belonging = rowMeans(select(., 1:5), na.rm = TRUE),
academic_self_concept = rowMeans(select(., 7:12), na.rm = TRUE),
perceived_stress = rowMeans(select(., 13:18), na.rm = TRUE),
perceived_discrimination = rowMeans(select(., 19:24), na.rm = TRUE),
respect_diversity = rowMeans(select(., 25:31), na.rm = TRUE)
) %>%
select(belonging, academic_self_concept, perceived_stress, perceived_discrimination, respect_diversity)
```

```{r}
cor_matrix <- cor(subscale_scores)
cor_matrix
```

